# Generated by Django 5.2.4 on 2025-07-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumb_url', models.ImageField(upload_to='thumbnails/')),
                ('full_url', models.ImageField(upload_to='fullsize/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
