# Generated by Django 5.2.4 on 2025-07-15 13:43

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cut_1',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Photo.upload_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='cut_2',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Photo.upload_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='cut_3',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Photo.upload_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='cut_4',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Photo.upload_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='full_url',
            field=models.ImageField(upload_to=main.models.Photo.upload_path),
        ),
    ]
